import type { User } from '@/types/auth.types';
import type { Assignment } from '@/types/assignment.types';
import type { Course } from '@/types/course.types';
import type { Quiz } from '@/types/quiz.types';
import type { Certificate } from '@/types/certificate.types';
import type { Target } from '@/types/target.types';
import type { AttendanceRecord } from '@/types/attendance.types';

export const mockUser: User = {
  id: 'user_001',
  employee_code: 'HT-STF-1001',
  full_name: 'Priya Sharma',
  mobile: '9876543210',
  email: 'priya.sharma.staff@hometown.in',
  role: 'STAFF',
  store_id: 'store_001',
  store_name: 'HomeTown Mumbai Thane',
  region_id: 'region_001',
  designation: 'Senior Sales Associate',
  department: 'Furniture',
  date_of_joining: '2023-04-01',
  status: 'active',
};

export const ASSIGNED_STORE = {
  id: 'store_001',
  name: 'HomeTown Mumbai Thane',
  latitude: 19.2183,
  longitude: 72.9781,
  radiusMeters: 150,
  address: 'Thane, Mumbai, Maharashtra',
};

export const mockAttendance: AttendanceRecord[] = [
  { id: 'a1', date: '2026-05-19', check_in_time: '09:58 AM', check_out_time: '07:02 PM', check_in_status: 'success', check_out_status: 'success', check_in_distance_meters: 42, store_name: 'HomeTown Mumbai Thane', status: 'present' },
  { id: 'a2', date: '2026-05-18', check_in_time: '10:05 AM', check_out_time: '07:00 PM', check_in_status: 'success', check_out_status: 'success', check_in_distance_meters: 88, store_name: 'HomeTown Mumbai Thane', status: 'present' },
  { id: 'a3', date: '2026-05-17', check_in_time: null, check_out_time: null, check_in_status: 'error', check_out_status: null, check_in_distance_meters: null, store_name: 'HomeTown Mumbai Thane', status: 'absent' },
  { id: 'a4', date: '2026-05-16', check_in_time: '10:15 AM', check_out_time: '07:10 PM', check_in_status: 'success', check_out_status: 'success', check_in_distance_meters: 63, store_name: 'HomeTown Mumbai Thane', status: 'late' },
  { id: 'a5', date: '2026-05-15', check_in_time: '09:50 AM', check_out_time: '07:05 PM', check_in_status: 'success', check_out_status: 'success', check_in_distance_meters: 35, store_name: 'HomeTown Mumbai Thane', status: 'present' },
  { id: 'a6', date: '2026-05-14', check_in_time: null, check_out_time: null, check_in_status: 'error', check_out_status: null, check_in_distance_meters: null, store_name: 'HomeTown Mumbai Thane', status: 'absent' },
  { id: 'a7', date: '2026-05-13', check_in_time: '09:55 AM', check_out_time: '07:00 PM', check_in_status: 'success', check_out_status: 'success', check_in_distance_meters: 55, store_name: 'HomeTown Mumbai Thane', status: 'present' },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'asgn1',
    title: 'Upload Sofa Display Photo',
    description: 'Capture and upload a high-quality photo of the current sofa display area on the ground floor. Ensure the complete display is visible with proper lighting.',
    assignment_type: 'image_upload',
    priority: 'high',
    due_date: '2026-05-22',
    assigned_by_name: 'Ramesh Kumar (Store Manager)',
    status: 'assigned',
    attachments: [],
    created_at: '2026-05-18',
    updated_at: '2026-05-18',
  },
  {
    id: 'asgn2',
    title: 'Submit Competitor Price Check PDF',
    description: 'Visit 2 competitor stores and document their sofa and mattress pricing in the provided template. Submit as PDF.',
    assignment_type: 'pdf_upload',
    priority: 'urgent',
    due_date: '2026-05-20',
    assigned_by_name: 'HO Sales Team',
    status: 'overdue',
    attachments: [],
    created_at: '2026-05-13',
    updated_at: '2026-05-19',
  },
  {
    id: 'asgn3',
    title: 'Complete Weekly Product Knowledge Task',
    description: 'Study the new Modular Kitchen catalogue and answer the 10-question knowledge check at the end.',
    assignment_type: 'text',
    priority: 'medium',
    due_date: '2026-05-25',
    assigned_by_name: 'HO Training Team',
    status: 'in_progress',
    attachments: [],
    created_at: '2026-05-15',
    updated_at: '2026-05-17',
  },
  {
    id: 'asgn4',
    title: 'Upload Festive Display Setup',
    description: 'After setting up the festive display as per VM guidelines, upload 3 photos from different angles.',
    assignment_type: 'image_upload',
    priority: 'high',
    due_date: '2026-05-28',
    assigned_by_name: 'VM Department',
    status: 'submitted',
    attachments: [],
    created_at: '2026-05-16',
    updated_at: '2026-05-19',
  },
  {
    id: 'asgn5',
    title: 'Customer Interaction Report',
    description: 'Document your top 5 customer interactions this week: product category, customer need, outcome, and follow-up required.',
    assignment_type: 'text',
    priority: 'low',
    due_date: '2026-05-24',
    assigned_by_name: 'Ramesh Kumar (Store Manager)',
    status: 'approved',
    attachments: [],
    created_at: '2026-05-14',
    updated_at: '2026-05-20',
  },
];

export const mockCourses: Course[] = [
  {
    id: 'c1',
    title: 'HomeTown Brand Induction',
    description: 'Learn HomeTown\'s story, brand values, product range, customer promise, and service standards.',
    category: 'Brand & Culture',
    difficulty_level: 'beginner',
    estimated_duration_minutes: 45,
    passing_score: 70,
    certificate_enabled: true,
    progress_percentage: 100,
    status: 'completed',
  },
  {
    id: 'c2',
    title: 'Furniture Product Knowledge',
    description: 'Deep dive into HomeTown\'s furniture categories: sofas, beds, wardrobes, dining sets, and storage.',
    category: 'Product Knowledge',
    difficulty_level: 'beginner',
    estimated_duration_minutes: 60,
    passing_score: 70,
    certificate_enabled: true,
    progress_percentage: 100,
    status: 'completed',
  },
  {
    id: 'c3',
    title: 'Sofa Selling Masterclass',
    description: 'Advanced techniques for sofa sales: needs analysis, fabric knowledge, objection handling, and upselling.',
    category: 'Sales Training',
    difficulty_level: 'intermediate',
    estimated_duration_minutes: 90,
    passing_score: 75,
    certificate_enabled: true,
    progress_percentage: 60,
    status: 'in_progress',
  },
  {
    id: 'c4',
    title: 'Mattress Recommendation Training',
    description: 'Sleep science basics, mattress types — orthopedic, memory foam, coir — and customer consultation techniques.',
    category: 'Product Knowledge',
    difficulty_level: 'intermediate',
    estimated_duration_minutes: 75,
    passing_score: 75,
    certificate_enabled: true,
    progress_percentage: 0,
    status: 'not_started',
  },
  {
    id: 'c5',
    title: 'Modular Kitchen Basics',
    description: 'Introduction to modular kitchen categories, configurations, materials, and lead generation techniques.',
    category: 'Product Knowledge',
    difficulty_level: 'intermediate',
    estimated_duration_minutes: 80,
    passing_score: 70,
    certificate_enabled: true,
    progress_percentage: 0,
    status: 'not_started',
  },
  {
    id: 'c6',
    title: 'Home Decor Styling Guide',
    description: 'Color theory, styling trends, room concepts, and how to help customers create cohesive decor looks.',
    category: 'Styling & Design',
    difficulty_level: 'beginner',
    estimated_duration_minutes: 50,
    passing_score: 70,
    certificate_enabled: false,
    progress_percentage: 0,
    status: 'not_started',
  },
  {
    id: 'c7',
    title: 'Customer Service Excellence',
    description: 'Delivering world-class customer service: greeting, probing, handling complaints, and post-sale follow-up.',
    category: 'Customer Handling',
    difficulty_level: 'beginner',
    estimated_duration_minutes: 55,
    passing_score: 70,
    certificate_enabled: true,
    progress_percentage: 100,
    status: 'completed',
  },
  {
    id: 'c8',
    title: 'Visual Merchandising Standards',
    description: 'HomeTown VM guidelines: display norms, planogram compliance, lighting, pricing, and seasonal themes.',
    category: 'Store Operations',
    difficulty_level: 'beginner',
    estimated_duration_minutes: 40,
    passing_score: 70,
    certificate_enabled: false,
    progress_percentage: 100,
    status: 'completed',
  },
];

export const mockQuizzes: Quiz[] = [
  {
    id: 'qz1',
    course_id: 'c2',
    title: 'Furniture Product Knowledge Quiz',
    description: 'Test your knowledge of HomeTown furniture categories.',
    time_limit_minutes: 10,
    passing_score: 70,
    max_attempts: 3,
    attempts_used: 0,
    questions: [
      { id: 'q1', question_text: 'Which wood type is most durable for outdoor furniture?', question_type: 'single_choice', marks: 10, options: [{ id: 'a', option_text: 'Teak', is_correct: true }, { id: 'b', option_text: 'Pine', is_correct: false }, { id: 'c', option_text: 'MDF', is_correct: false }, { id: 'd', option_text: 'Plywood', is_correct: false }] },
      { id: 'q2', question_text: 'What does "sectional sofa" mean?', question_type: 'single_choice', marks: 10, options: [{ id: 'a', option_text: 'A 2-seater sofa', is_correct: false }, { id: 'b', option_text: 'An L-shaped modular sofa', is_correct: true }, { id: 'c', option_text: 'A reclinable sofa', is_correct: false }, { id: 'd', option_text: 'A wall-mounted sofa', is_correct: false }] },
      { id: 'q3', question_text: 'Memory foam was originally developed by NASA.', question_type: 'true_false', marks: 10, options: [{ id: 'a', option_text: 'True', is_correct: true }, { id: 'b', option_text: 'False', is_correct: false }] },
      { id: 'q4', question_text: 'Which fabric is easiest to clean?', question_type: 'single_choice', marks: 10, options: [{ id: 'a', option_text: 'Velvet', is_correct: false }, { id: 'b', option_text: 'Microfiber', is_correct: true }, { id: 'c', option_text: 'Linen', is_correct: false }, { id: 'd', option_text: 'Cotton', is_correct: false }] },
      { id: 'q5', question_text: 'Standard HomeTown sofa warranty duration?', question_type: 'single_choice', marks: 10, options: [{ id: 'a', option_text: '1 year', is_correct: false }, { id: 'b', option_text: '2 years', is_correct: false }, { id: 'c', option_text: '3 years', is_correct: true }, { id: 'd', option_text: '5 years', is_correct: false }] },
    ],
  },
  {
    id: 'qz2',
    course_id: 'c3',
    title: 'Sofa Sales Quiz',
    description: 'Test your sofa sales techniques and product knowledge.',
    time_limit_minutes: 8,
    passing_score: 75,
    max_attempts: 3,
    attempts_used: 1,
    questions: [
      { id: 'q1', question_text: 'Which selling technique should you use first with a new customer?', question_type: 'single_choice', marks: 10, options: [{ id: 'a', option_text: 'Show the most expensive product', is_correct: false }, { id: 'b', option_text: 'Greet and probe for needs', is_correct: true }, { id: 'c', option_text: 'Offer a discount immediately', is_correct: false }, { id: 'd', option_text: 'Show the latest catalogue', is_correct: false }] },
      { id: 'q2', question_text: 'Upselling means suggesting a cheaper alternative.', question_type: 'true_false', marks: 10, options: [{ id: 'a', option_text: 'True', is_correct: false }, { id: 'b', option_text: 'False', is_correct: true }] },
      { id: 'q3', question_text: 'Microfiber sofa benefit for families with pets?', question_type: 'single_choice', marks: 10, options: [{ id: 'a', option_text: 'Lower cost', is_correct: false }, { id: 'b', option_text: 'Easy to clean and pet-hair resistant', is_correct: true }, { id: 'c', option_text: 'More colors', is_correct: false }, { id: 'd', option_text: 'Softer feel', is_correct: false }] },
    ],
  },
];

export const mockCertificates: Certificate[] = [
  { id: 'cert1', certificate_code: 'HT-CERT-2026-001', course_title: 'Sofa Expert Level 1', employee_name: 'Priya Sharma', employee_id: 'HT-STF-1001', store_name: 'HomeTown Mumbai Thane', score: 88, certificate_url: '', issued_at: '2026-05-10', verification_url: 'https://karmyogi.hometown.in/verify/HT-CERT-2026-001', status: 'active' },
  { id: 'cert2', certificate_code: 'HT-CERT-2026-002', course_title: 'HomeTown Brand Induction', employee_name: 'Priya Sharma', employee_id: 'HT-STF-1001', store_name: 'HomeTown Mumbai Thane', score: 95, certificate_url: '', issued_at: '2026-04-05', verification_url: 'https://karmyogi.hometown.in/verify/HT-CERT-2026-002', status: 'active' },
  { id: 'cert3', certificate_code: 'HT-CERT-2026-003', course_title: 'Customer Service Excellence', employee_name: 'Priya Sharma', employee_id: 'HT-STF-1001', store_name: 'HomeTown Mumbai Thane', score: 82, certificate_url: '', issued_at: '2026-05-02', verification_url: 'https://karmyogi.hometown.in/verify/HT-CERT-2026-003', status: 'active' },
  { id: 'cert4', certificate_code: 'HT-CERT-2026-004', course_title: 'Furniture Product Knowledge', employee_name: 'Priya Sharma', employee_id: 'HT-STF-1001', store_name: 'HomeTown Mumbai Thane', score: 92, certificate_url: '', issued_at: '2026-04-20', verification_url: 'https://karmyogi.hometown.in/verify/HT-CERT-2026-004', status: 'active' },
];

export const mockTargets: Target[] = [
  { id: 'wt1', target_type: 'revenue', metric_type: 'sales_amount', category: 'Overall Revenue', period_type: 'weekly', period_start: '2026-05-18', period_end: '2026-05-24', target_value: 100000, achieved_value: 68000, achievement_percentage: 68, status: 'in_progress', unit: '₹' },
  { id: 'wt2', target_type: 'sales', metric_type: 'sales_amount', category: 'Sofas', period_type: 'weekly', period_start: '2026-05-18', period_end: '2026-05-24', target_value: 50000, achieved_value: 35000, achievement_percentage: 70, status: 'in_progress', unit: '₹' },
  { id: 'wt3', target_type: 'leads', metric_type: 'leads_generated', category: 'Modular Kitchen', period_type: 'weekly', period_start: '2026-05-18', period_end: '2026-05-24', target_value: 5, achieved_value: 2, achievement_percentage: 40, status: 'in_progress', unit: '' },
  { id: 'mt1', target_type: 'revenue', metric_type: 'sales_amount', category: 'Overall Revenue', period_type: 'monthly', period_start: '2026-05-01', period_end: '2026-05-31', target_value: 450000, achieved_value: 285000, achievement_percentage: 63, status: 'in_progress', unit: '₹' },
  { id: 'mt2', target_type: 'sales', metric_type: 'sales_amount', category: 'Beds & Wardrobes', period_type: 'monthly', period_start: '2026-05-01', period_end: '2026-05-31', target_value: 120000, achieved_value: 120000, achievement_percentage: 100, status: 'achieved', unit: '₹' },
  { id: 'mt3', target_type: 'sales', metric_type: 'sales_amount', category: 'Sofas', period_type: 'monthly', period_start: '2026-05-01', period_end: '2026-05-31', target_value: 180000, achieved_value: 105000, achievement_percentage: 58, status: 'in_progress', unit: '₹' },
  { id: 'mt4', target_type: 'sales', metric_type: 'sales_amount', category: 'Mattresses', period_type: 'monthly', period_start: '2026-05-01', period_end: '2026-05-31', target_value: 80000, achieved_value: 82000, achievement_percentage: 102, status: 'exceeded', unit: '₹' },
  { id: 'mt5', target_type: 'training', metric_type: 'training_completion', category: 'Course Completion', period_type: 'monthly', period_start: '2026-05-01', period_end: '2026-05-31', target_value: 5, achieved_value: 3, achievement_percentage: 60, status: 'in_progress', unit: '' },
  { id: 'yt1', target_type: 'revenue', metric_type: 'sales_amount', category: 'Annual Revenue', period_type: 'yearly', period_start: '2026-01-01', period_end: '2026-12-31', target_value: 5400000, achieved_value: 3120000, achievement_percentage: 58, status: 'in_progress', unit: '₹' },
  { id: 'yt2', target_type: 'training', metric_type: 'training_completion', category: 'Certifications Target', period_type: 'yearly', period_start: '2026-01-01', period_end: '2026-12-31', target_value: 10, achieved_value: 4, achievement_percentage: 40, status: 'in_progress', unit: '' },
];

export const mockNotifications = [
  { id: 'n1', title: 'New Assignment', message: 'Upload Sofa Display Photo has been assigned to you.', type: 'assignment', read: false, created_at: '2026-05-20T09:00:00' },
  { id: 'n2', title: 'Course Due Tomorrow', message: 'Sofa Selling Masterclass quiz is due tomorrow. Complete it to earn your certificate.', type: 'course', read: false, created_at: '2026-05-19T18:00:00' },
  { id: 'n3', title: 'Certificate Generated', message: 'Your Customer Service Excellence certificate is ready to download.', type: 'certificate', read: true, created_at: '2026-05-18T14:30:00' },
  { id: 'n4', title: 'Monthly Target Updated', message: 'Your May 2026 revenue target has been updated to ₹4,50,000.', type: 'target', read: true, created_at: '2026-05-17T10:00:00' },
  { id: 'n5', title: 'Attendance Reminder', message: 'You have not checked in today. Please mark your attendance.', type: 'attendance', read: true, created_at: '2026-05-20T10:15:00' },
  { id: 'n6', title: 'Quiz Pending', message: 'Mattress Recommendation Quiz is now available. Complete it to earn 10 points.', type: 'quiz', read: false, created_at: '2026-05-19T08:00:00' },
  { id: 'n7', title: 'Assignment Approved', message: 'Your Customer Interaction Report has been approved by your manager.', type: 'assignment', read: true, created_at: '2026-05-19T16:45:00' },
];

export const mockDocuments = [
  { id: 'd1', file_name: 'Customer_Interaction_Report_May.pdf', file_type: 'PDF', file_size: 245000, upload_status: 'uploaded', approval_status: 'approved', uploaded_at: '2026-05-18' },
  { id: 'd2', file_name: 'Sofa_Display_Photo_May.jpg', file_type: 'JPG', file_size: 1800000, upload_status: 'uploaded', approval_status: 'pending', uploaded_at: '2026-05-19' },
  { id: 'd3', file_name: 'Competitor_Price_Check.pdf', file_type: 'PDF', file_size: 512000, upload_status: 'uploaded', approval_status: 'rejected', uploaded_at: '2026-05-15' },
];
